name: writers_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  shared_preferences: ^2.0.5
  loading: ^1.0.2
  speech_to_text: ^3.2.0
  liquid_pull_to_refresh: ^2.0.0
#  cloud_firestore: any
#  flutter_expanded_tile: ^0.2.1
  permission_handler: ^5.1.0+2
  font_awesome_flutter: ^8.11.0
  firebase_core: any
  google_sign_in: ^4.5.9
  firebase_auth: ^0.18.4+1
  flutter_colorpicker: ^0.3.5
  lit_firebase_auth: ^0.3.0
  firebase_auth_oauth: ^0.2.0
  share: ^0.6.5+4
  provider: ^4.3.2+3
  toast: ^0.1.5

  firebase_wrapper:
    path: ../shared_lib/firebase_wrapper
  article_themedata:
    path: ../shared_article_packages/article_themedata
  animations:
    path: ../shared_lib/animations
  profile_page:
    path: ../shared_article_packages/profile_page
  articleclasses:
    path: ../shared_article_packages/articleclasses
  articlewidgets:
    path: ../shared_article_packages/articlewidgets

  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_native_splash: ^0.3.2
#  flutter_native_splash:
#    color: "42a5f5"
#    #image: assets/splash.png

dev_dependencies:
  flutter_launcher_name:
  test: ^1.15.7
  flutter_test:
    sdk: flutter

flutter_launcher_name:
  name: "Writaz"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
flutter_native_splash:
  color: "#4e342e"
  image: assets/light-coffee.png
  fill: true

  #web: false
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
